{% set name = "pyilluminate" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e15ba105b9552cf0056c305d0f906f317c1bdd439c93b7a59da2c0d5eeac5f0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyserial
    - dataclasses
    - xarray
    - filelock

test:
  imports:
    - pyilluminate

about:
  home: https://github.com/ramonaoptics/pyilluminate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface for controlling the Illuminate boards.

extra:
  recipe-maintainers:
    - hmaarrfk
