{% set name = "pyilluminate" %}
{% set version = "0.5.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee57e3ca087201389753153bbdf470ef973e382c83babdcd85d7a001fb28ba1b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyserial
    - dataclasses
    - xarray
    - filelock

test:
  imports:
    - pyilluminate

about:
  home: https://github.com/ramonaoptics/pyilluminate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface for controlling the Illuminate boards.

extra:
  recipe-maintainers:
    - hmaarrfk
