{% set name = "pyilluminate" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ecf212fd180736d6fb5eda947f3a8da1dad1905a6a00ff3eb3923f9c6a6074b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyserial
    - dataclasses
    - xarray
    - filelock

test:
  imports:
    - pyilluminate

about:
  home: https://github.com/ramonaoptics/pyilluminate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface for controlling the Illuminate boards.

extra:
  recipe-maintainers:
    - hmaarrfk
