{% set name = "pyilluminate" %}
{% set version = "0.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea7f1aab58ec5aca45d3a13ff5e7fcde5c07ed34c6d6e94a12f2726a181cd422

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyserial
    - dataclasses
    - xarray
    - filelock

test:
  imports:
    - pyilluminate

about:
  home: https://github.com/ramonaoptics/pyilluminate
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface for controlling the Illuminate boards.

extra:
  recipe-maintainers:
    - hmaarrfk
